name: Release Unraid Plugin

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Includes checkout v7, setup-go v6, and add-and-commit v10.
      - uses: dkaser/unraid-plugin-release-action@dd44159f2d27c70b101db9cf76d6f11babc3e6f0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_version: ${{ github.event.release.name }}
          plg_branch: main
          build_script: cp README.md src/usr/local/emhttp/plugins/fanctrlplus2/README.md
